-- MySQL Script generated by MySQL Workbench
-- Wed Nov 12 18:14:40 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema f1telemetria
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `f1telemetria` ;

-- -----------------------------------------------------
-- Schema f1telemetria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `f1telemetria` DEFAULT CHARACTER SET utf8 ;
USE `f1telemetria` ;

-- -----------------------------------------------------
-- Table `f1telemetria`.`equipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `f1telemetria`.`equipo` ;

CREATE TABLE IF NOT EXISTS `f1telemetria`.`equipo` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `f1telemetria`.`piloto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `f1telemetria`.`piloto` ;

CREATE TABLE IF NOT EXISTS `f1telemetria`.`piloto` (
  `nombre` VARCHAR(250) NOT NULL,
  `numero` INT NULL DEFAULT NULL,
  `nacionalidad` INT NULL DEFAULT NULL,
  `nivelTecnico` INT NULL DEFAULT NULL COMMENT 'techLevel',
  `plataforma` INT NULL DEFAULT NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `f1telemetria`.`circuito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `f1telemetria`.`circuito` ;

CREATE TABLE IF NOT EXISTS `f1telemetria`.`circuito` (
  `id` INT NOT NULL COMMENT 'Mexico : 19',
  `nombre` VARCHAR(250) NULL DEFAULT NULL,
  `pais` VARCHAR(250) NULL DEFAULT NULL,
  `longitud` INT NOT NULL,
  `velocidadPitLine` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;
insert into circuito values (15, "Circuito de las Americas - Austin / Texas", "Estados Unidos", 5514, 80), (31, "Las Vegas / Nevada", "Estados Unidos", 6200, 80);


-- -----------------------------------------------------
-- Table `f1telemetria`.`sesion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `f1telemetria`.`sesion` ;

CREATE TABLE IF NOT EXISTS `f1telemetria`.`sesion` (
  `uid` VARCHAR(20) NOT NULL,
  `tipo` INT NOT NULL COMMENT 'Time Trial : 18',
  `circuitoId` INT NOT NULL,
  -- `clima` INT NOT NULL COMMENT 'Despejado: 0\n\nOJO! Habria que controlar si cambia con una N:N',
  clima int default null,
  `cocheJugadorId` INT NOT NULL,
  -- `vueltasTotales` INT NOT NULL COMMENT 'Time Trial : 1',
  vueltasTotales int default null,
  `fecha` TIMESTAMP NULL DEFAULT current_timestamp,
  INDEX `fk_sesion_circuito_idx` (`circuitoId` ASC) VISIBLE,
  PRIMARY KEY (`uid`),
  CONSTRAINT `fk_sesion_circuito` FOREIGN KEY (`circuitoId`) REFERENCES `f1telemetria`.`circuito` (`id`)
    -- ON DELETE NO ACTION
    -- ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `f1telemetria`.`sesionParticipaPiloto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `f1telemetria`.`sesionParticipaPiloto` ;

CREATE TABLE IF NOT EXISTS `f1telemetria`.`sesionParticipaPiloto` (
  `sesionUid` VARCHAR(20) NOT NULL,
  `pilotoNombre` VARCHAR(250) NOT NULL,
  `equipoId` INT NOT NULL,
  `indiceArray` INT NOT NULL,
  `ia` TINYINT NOT NULL,
  `miTelemetria` TINYINT NOT NULL,
  `miEquipo` TINYINT NOT NULL,
  `nivelTecnico` INT NULL DEFAULT NULL COMMENT 'Se guarda en \"sesionParticipaPilotoConduciendoEquipo\" pero se actualiza el valor en \"piloto\". ¿Solo si aumenta, que es lo normal?',
  INDEX `fk_sesionParticipaPiloto_sesion1_idx` (`sesionUid` ASC) VISIBLE,
  INDEX `fk_sesionParticipaPiloto_piloto1_idx` (`pilotoNombre` ASC) VISIBLE,
  INDEX `fk_sesionParticipaPilotoConduciendoEquipo_equipo1_idx` (`equipoId` ASC) VISIBLE,
  PRIMARY KEY (`sesionUid`, `pilotoNombre`),
  CONSTRAINT `fk_sesionParticipaPiloto_sesion1`
    FOREIGN KEY (`sesionUid`)
    REFERENCES `f1telemetria`.`sesion` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sesionParticipaPiloto_piloto1`
    FOREIGN KEY (`pilotoNombre`)
    REFERENCES `f1telemetria`.`piloto` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sesionParticipaPilotoConduciendoEquipo_equipo1`
    FOREIGN KEY (`equipoId`)
    REFERENCES `f1telemetria`.`equipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `f1telemetria`.`reglaje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `f1telemetria`.`reglaje` ;

CREATE TABLE IF NOT EXISTS `f1telemetria`.`reglaje` (
  `id` VARCHAR(64) NOT NULL,
  `frontWing` INT NOT NULL,
  `rearWing` INT NOT NULL,
  `onThrottle` INT NOT NULL,
  `offThrottle` INT NOT NULL,
  `frontCamber` FLOAT NOT NULL,
  `rearCamber` FLOAT NOT NULL,
  `frontToe` FLOAT NOT NULL,
  `rearToe` FLOAT NOT NULL,
  `frontSuspension` INT NOT NULL,
  `rearSuspension` INT NOT NULL,
  `frontAntiRollBar` INT NOT NULL,
  `rearAntiRollBar` INT NOT NULL,
  `frontSuspensionHeight` INT NOT NULL,
  `rearSuspensionHeight` INT NOT NULL,
  `breakePressure` INT NOT NULL,
  `breakBias` INT NOT NULL,
  `engineBraking` INT NOT NULL,
  `rearLeftTyrePressure` FLOAT NOT NULL,
  `rearRightTyrePressure` FLOAT NOT NULL,
  `frontLeftTyrePressure` FLOAT NOT NULL,
  `frontRightTyrePressure` FLOAT NOT NULL,
  `ballast` INT NOT NULL,
  `fuelLoad` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `f1telemetria`.`participanteUsaReglaje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `f1telemetria`.`participanteUsaReglaje` ;

CREATE TABLE IF NOT EXISTS `f1telemetria`.`participanteUsaReglaje` (
  `sesionUid` VARCHAR(20) NOT NULL,
  `pilotoNombre` VARCHAR(250) NOT NULL,
  `vueltaInicio` INT NOT NULL,
  `reglajeId` VARCHAR(64) NOT NULL,
  `vueltaFinal` INT NULL DEFAULT NULL,
  PRIMARY KEY (`sesionUid`, `pilotoNombre`, `vueltaInicio`),
  INDEX `fk_participanteReglaje_sesionParticipaPilotoConduciendoEqui_idx1` (`sesionUid` ASC, `pilotoNombre` ASC) VISIBLE,
  INDEX `fk_participanteReglaje_reglaje2_idx` (`reglajeId` ASC) VISIBLE,
  CONSTRAINT `fk_participanteReglaje_sesionParticipaPilotoConduciendoEquipo2`
    FOREIGN KEY (`sesionUid` , `pilotoNombre`)
    REFERENCES `f1telemetria`.`sesionParticipaPiloto` (`sesionUid` , `pilotoNombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_participanteReglaje_reglaje2`
    FOREIGN KEY (`reglajeId`)
    REFERENCES `f1telemetria`.`reglaje` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `f1telemetria`.`juego`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `f1telemetria`.`juego` ;

CREATE TABLE IF NOT EXISTS `f1telemetria`.`juego` (
  `id` INT NOT NULL,
  `indiceArray` INT NOT NULL,
  `compuesto` INT NOT NULL,
  `color` INT NULL,
  `desgaste` INT NULL COMMENT '\"Wear\"',
  `disponible` TINYBLOB NOT NULL,
  `sesionRecomendada` INT NULL,
  `vidaMedia` INT NULL,
  `vidaRestante` INT NULL,
  `deltaVuelta` FLOAT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `f1telemetria`.`participanteUsaJuego`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `f1telemetria`.`participanteUsaJuego` ;

CREATE TABLE IF NOT EXISTS `f1telemetria`.`participanteUsaJuego` (
  `sesionUid` VARCHAR(20) NOT NULL,
  `pilotoNombre` VARCHAR(250) NOT NULL,
  `vueltaInicio` INT NOT NULL,
  `juego_id` INT NOT NULL,
  `vueltaFinal` INT NULL DEFAULT NULL,
  INDEX `fk_participanteUsaJuego_sesionParticipaPiloto1_idx` (`sesionUid` ASC, `pilotoNombre` ASC) VISIBLE,
  PRIMARY KEY (`sesionUid`, `pilotoNombre`, `vueltaInicio`),
  INDEX `fk_participanteUsaJuego_juego1_idx` (`juego_id` ASC) VISIBLE,
  CONSTRAINT `fk_participanteUsaJuego_sesionParticipaPiloto1`
    FOREIGN KEY (`sesionUid` , `pilotoNombre`)
    REFERENCES `f1telemetria`.`sesionParticipaPiloto` (`sesionUid` , `pilotoNombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_participanteUsaJuego_juego1`
    FOREIGN KEY (`juego_id`)
    REFERENCES `f1telemetria`.`juego` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `f1telemetria`.`participanteTieneJuego`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `f1telemetria`.`participanteTieneJuego` ;

CREATE TABLE IF NOT EXISTS `f1telemetria`.`participanteTieneJuego` (
  `sesionUid` VARCHAR(20) NOT NULL,
  `pilotoNombre` VARCHAR(250) NOT NULL,
  `juego_id` INT NOT NULL,
  INDEX `fk_participanteTieneJuego_sesionParticipaPiloto1_idx` (`sesionUid` ASC, `pilotoNombre` ASC) VISIBLE,
  INDEX `fk_participanteTieneJuego_juego1_idx` (`juego_id` ASC) VISIBLE,
  PRIMARY KEY (`sesionUid`, `pilotoNombre`, `juego_id`),
  CONSTRAINT `fk_participanteTieneJuego_sesionParticipaPiloto1`
    FOREIGN KEY (`sesionUid` , `pilotoNombre`)
    REFERENCES `f1telemetria`.`sesionParticipaPiloto` (`sesionUid` , `pilotoNombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_participanteTieneJuego_juego1`
    FOREIGN KEY (`juego_id`)
    REFERENCES `f1telemetria`.`juego` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
